os:
  - linux
  - osx
language: generic
sudo: required
osx_image: xcode10.2
dist: trusty
env:
  - SWIFT_VERSION=4.2
  - SWIFT_VERSION=5.0
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test

