matrix:
  include:
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION=4.2
        - MAJOR_VERSION=4.2
    - os: osx
      language: generic
      sudo: required
      osx_image: xcode10
      env:
        - SWIFT_VERSION=4.2
        - MAJOR_VERSION=4.2
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test -Xswiftc -swift-version -Xswiftc $MAJOR_VERSION

